version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: gohost
      MYSQL_DATABASE: gohost
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
volumes:
  dbdata:
