version: "3"
services:
  # gh-app:
  #   build: .
  #   tty: true
  #   restart: always
  #   ports:
  #     - "5050:3000"
  #   command: go run ./cmd/gohost-server/main.go
  #   depends_on:
  #     - db
  gh-adminer:
    container_name: gh-adminer
    hostname: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 25750:8080
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: gohost
      MYSQL_DATABASE: gohost
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
volumes:
  dbdata:
