version: "3"
services:
  gh-app:
    build: .
    tty: true
    restart: always
    ports:
      - "3000:3000"
    command: go run main.go
    depends_on:
      - gh-db
  gh-adminer:
    container_name: gh-adminer
    hostname: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 25750:8080
    depends_on:
      - gh-db
  gh-db:
    container_name: gh-db
    ports:
      - 3306:3306
    volumes:
      - "./mysql:/var/lib/mysql"
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      TZ: Asia/Tokyo
